name: Test with K3d

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest # [self-hosted, linux, x64]
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2

      - name: Check kubectl
        id: check-kubectl
        run: |
          if [ "kubectl version" != 0 ]; then
            curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
            chmod +x ./kubectl
            mv ./kubectl /usr/local/bin/kubectl
          fi

      - name: Install k3d
        run: |
          wget -q -O - https://raw.githubusercontent.com/rancher/k3d/main/install.sh | bash
          k3d cluster create mycluster
          k3d kubeconfig merge mycluster --switch-context
      - name: Deploy drupal
        run: |
          kubectl cluster-info
          kubectl create namespace drupal
          kubectl apply -f app/
      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
      - name: Create OpenFaaS namespaces
        run: |
          kubectl apply -f https://raw.githubusercontent.com/openfaas/faas-netes/master/namespaces.yml
          kubectl get namespaces
      - name: Add the OpenFaaS helm chart
        run: |
          helm repo add openfaas https://openfaas.github.io/faas-netes/
      - name: Deploy OpenFaaS from the helm chart
        run: |
          helm repo update \
            & helm upgrade openfaas --install openfaas/openfaas \
              --namespace openfaas  \
              --set functionNamespace=openfaas-fn \
              --set generateBasicAuth=true \
              --set openfaasPRO=false
