name: Test with K3d

on: [push]

jobs:
  dev_env:
    runs-on: ubuntu-latest # [self-hosted, linux, x64]
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2

      - name: Make scripts executable
        run: find scripts/ -type f -iname "*.sh" -exec chmod +x {} \;

      - name: Prerare the devolpment environment
        run: scripts/dev_env.sh
        shell: bash
